spring:
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  datasource:
    username: "sa"
    password: ""
    url: "jdbc:h2:mem:testdb;CASE_INSENSITIVE_IDENTIFIERS=TRUE"
    driverClassName: "org.h2.Driver"
logging:
  level:
    root: INFO
    org:
      springframework:
        jdbc:
          core: "TRACE"
  liquibase: INFO
  com:
    amitph: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %-5p | %X{mdcData} | [%thread] %logger{5}:%L - %msg%n"
